config/routes.rb
Rails.application.routes.draw do
  get 'invite/:link_id', to: 'band_members#invite'
  get 'bands/:id/delete', to: 'bands#delete', as: 'delete_band'
  get 'bands/:band_id/albums/:id/delete', to: 'albums#delete', as: 'delete_band_album'
  get 'bands/:band_id/band_members/:id/delete', to: 'band_members#delete', as: 'delete_band_band_member'
  get "/takedown-guidance", to: "welcome#notification", as: "takedown_guidance"
  resources :users, only: [:edit, :update, :show]
  resources :bands do
    collection do
      match 'search' => 'bands#search', via: [:get, :post], as: :search
    end
    resources :band_members, only: [:create, :update, :destroy, :edit]
    resources :albums, only: [:new, :create, :destroy, :edit, :update] do
      resources :songs, only: [:new, :update, :edit, :create, :destroy]
    end
    resources :user_reviews, only: [:create, :update, :destroy]
    resources :events, only: [:show, :new, :update, :edit, :create, :destroy]
  end
  root 'welcome#index'
  get "/auth/:provider/callback" => 'sessions#create'
  resources :sessions, only: [:create, :destroy]
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs
  belongs_to :band
  has_many :user_review
  mount_uploader :pict, AttachmentUploader
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :albums
  has_many :band_members
  has_many :users, through: :band_members
  has_many :user_reviews
  has_many :events
  mount_uploader :logo, AttachmentUploader
  validates :name, presence: true
end

app/models/band_member.rb
class BandMember < ApplicationRecord
  belongs_to :user
  belongs_to :band
  has_and_belongs_to_many :instruments
  validates :nickname, presence: true
  validates :instruments, presence: true, unless: ->(band_member) { band_member.another_instrument.present? }
  validates :another_instrument, presence: true, unless: ->(band_member) { band_member.instruments.present? }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :event_type
  belongs_to :band
  validates :header, presence: true
  validates :text, presence: true
end

app/models/event_type.rb
class EventType < ApplicationRecord
  has_many :events
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_and_belongs_to_many :band_members
  validates :name, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  mount_uploader :file, AttachmentUploader
  validates :name, presence: true
  validates :file, presence: true
  validates :priority, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :band_members
  has_many :bands, through: :band_members
  has_many :user_reviews
  validates :name, presence: true
  mount_uploader :avatar, AttachmentUploader
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.first_name if user.name.nil? || user.name.empty?
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :band
  belongs_to :user, optional: true
  validates :review, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: -1, less_than: 8 }
end

app/controllers/bands_controller.rb
require 'digest/sha1'
require 'pry'
class BandsController < ApplicationController
  before_action :check_user_logged_in, only: [:edit, :new, :create, :update]
  before_action only: [:edit, :update, :delete, :destroy] do
    check_user_got_right(@band)
  end

  def index
    @bands = @q.result.includes(:band_members, :albums)
  end

  def new
    @band = Band.new
    @band_member = BandMember.new
  end

  def search
    index
    render :index
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    @band.update(band_params)
    if @band.save

      redirect_to @band
    else
      redirect_to edit_band_path(@band), flash: { notice: 'An error occurred, please try it again' }
    end
  end

  def create
    @band = Band.new(band_params)
    instruments = params[:band][:band_members][:instruments].select { |value| value != "" }
    another_instrument = params[:band][:band_members][:another_instrument]
    if another_instrument == "" && instruments.empty?
      @instruments_empty = true
      render "new", flash: { notice: 'An error occurred, please try it again' }
      return
    else
      @instruments_empty = false
    end
    @band.rating = 3
    if @band.save
      link = Digest::SHA1.hexdigest [@band.id, rand].join
      @band_member = @band.band_members.new(band_member_params)
      @band_member.user = current_user
      instruments.each do |instrument|
        @band_member.instruments << Instrument.find(instrument)
      end
      @album = @band.albums.new(name: 'Basic')
      if @band_member.nickname == ""
        @band_member.nickname = current_user.name
      end
      if @band_member.save && @album.save && @band.update(:link => link)
        redirect_to @band
        return
      else
        @band.destroy
        render "new", flash: { notice: 'An error occurred, please try it again' }
        return
      end
    else
      render "new", flash: { notice: 'An error occurred, please try it again' }
      return
    end
  end

  def band_params
    params.require(:band).permit(:name, :description, :logo)
  end

  def band_member_params
    params[:band][:band_members].permit(:nickname, :instruments, :another_instrument)
  end

  def show
    @band = Band.find(params[:id])
    @band_members = @band.band_members
    @albums = @band.albums
    @reviews = @band.user_reviews.order('created_at DESC')
    unless current_user.nil?
      @new_review = UserReview.new(user: current_user)
    end
    @events = @band.events.order('date')
    @events.each do |event|
      if event.date < Date.yesterday
        event.destroy
      end
    end
    if @band.users.include?(current_user)
      @link = request.base_url + '/invite/' + @band.link
      render 'show_admin.html.slim'
    else
      @band.link = ""
    end
  end

  def delete
    @band = Band.find(params[:id])
  end

  def destroy
    @band = Band.find(params[:id])
    albums = @band.albums
    albums.destroy_all
    @band.events.destroy_all
    @band.band_members.map(&:destroy)
    @band.user_reviews.destroy_all
    @band.destroy
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
require 'pry'
class WelcomeController < ApplicationController
  def index
    if current_user
      @user_bands = current_user.bands
    end
    @top_bands = Band.order('rating DESC').take(5)
    @newest_bands = Band.order('created_at DESC').take(5)
    @q = Band.ransack(params[:q])
    @bands = @q.result(distinct: true)
  end

  def notification
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/band_members_helper.rb
module BandMembersHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.slim
div.container
  div.row
    div.col-md-12
      h1.red-name Welcome fellow metalhead
  div.row
    div class="col col-md-10"
      h3.dark-red On this page you will find most underground Metal bands!
  div.row

    -if current_user
      h3 Your bands:
      div.col-md-10
        table class="table"
          tbody
          - @user_bands.each do |band|
            tr
              td
                div class="col-md-3" 
                  = link_to band do
                    img> src=band.logo_url class="logo-preview"
                    = p band.name
                div.col-md-3
                  div class="star-ratings-css"
                    div.star-ratings-css-top style="width: #{band.rating * 22.5}%"
                      - 7.times do
                        span ★
                    div.star-ratings-css-bottom
                      - 7.times do
                        span ★
  div.row
    h3 Top bands:
    div.col-md-10
      table class="table"
        tbody
        - @top_bands.each do |band|
          tr
            td
              div class="col-md-3" 
                = link_to band do
                  img> src=band.logo_url class="logo-preview"
                  = p band.name
              div.col-md-3
                div class="star-ratings-css"
                  div.star-ratings-css-top style="width: #{band.rating * 22.5}%"
                    - 7.times do
                      span ★
                  div.star-ratings-css-bottom
                    - 7.times do
                      span ★

  div.row
    h3 Newest bands:
    div.col-md-10
      table class="table"
        tbody
        - @newest_bands.each do |band|
          tr
            td
              div class="col-md-3" 
                = link_to band do
                  img> src=band.logo_url class="logo-preview"
                  = p band.name
              div.col-md-3
                div class="star-ratings-css"
                  div.star-ratings-css-top style="width: #{band.rating * 22.5}%"
                    - 7.times do
                      span ★
                  div.star-ratings-css-bottom
                    - 7.times do
                      span ★
  div.row
    =link_to 'Show all bands', bands_path, :class => "btn-default btn-sm"

app/views/welcome/notification.html.slim
h1 Notification Rules

article
  p align="center" class="perex"
    em which govern the requirements for the users&lsquo; notifications regarding the content located on the Server


<h2 class="left">1. Notification regarding User Content that is in breach with the conditions of the Server and/or in breach of legal regulations</h2>

<ul class="conditions">
	<li><span>2.1.</span> The notification regarding User Content which is in violation of legal regulations and/or of the Conditions (in particular in violation of the Principles for User Content) (hereinafter referred to as &bdquo;the Notification&ldquo;) shall be delivered to the Provider in writing, under the following conditions:

	<ul>
		<li><span>2.1.1.</span> to the email address &#115;&#116;&#111;&#110;&#101;&#057;&#057;&#064;&#097;&#122;&#101;&#116;&#046;&#115;&#107</li>
	</ul>
	</li>
</ul>

<ul class="conditions">
	<li><span>2.2.</span> The Notification shall contain in particular the following information:

	<ul>
		<li><span>2.2.1.</span> information regarding the person who makes the notification, including contact information;</li>
		<li><span>2.2.2.</span> name of the Uploaded File (in the sense of the Conditions) and the whole unique URL address of the website of the file;</li>
		<li><span>2.2.3.</span> a declaration that contains the statement that the file is in violation of these Conditions or legal regulations;</li>
		<li><span>2.2.4.</span> an explanation of the reasons why the given file is in violation of these Conditions or of legal regulations;</li>
		<li><span>2.2.5.</span> in the event of a suspicion that the file violates copyright, the Notification shall also specify the following:
		<ul>
			<li><span>2.2.5.1.</span> which work the copyright is related to;</li>
			<li><span>2.2.5.2.</span> who is the authorized owner of the copyright;</li>
			<li><span>2.2.5.3.</span> and it shall be evidenced that the upload of the respective content onto the Server constitutes an illegal violation of the copyright.</li>
		</ul>
		</li>
		<li><span>2.2.6.</span> Further information necessary for assessing the illegal nature of the given file.</li>
	</ul>
	</li>
	<li><span>2.3.</span> The notifying party pledges to provide only correct, truthful, complete, rightful and justified information in the Notification.</li>
	<li><span>2.4.</span> The notifying party is responsible for making sure that the Notification is correct, truthful, complete, rightful and justified. The notifying party is liable for a Notification which in an incorrect, untruthful, and unjustified manner regards legal User Content, and the notifying party bears liability for damages caused to the User whose User Content the Notification concerns or to the Provider.</li>
	<li><span>2.5.</span> In the event that the Notification shall not contain at least the data and information stated in 2.2 hereof, such Notification need not be regarded by the Provider as having been properly made. In such an event, the Provider reserves the right to request additional information regarding the Notification.</li>
</ul>
</article>