config/routes.rb
Rails.application.routes.draw do
  get 'invite/:link_id', to: 'band_members#invite'
  get 'bands/:id/delete', to: 'bands#delete', as: 'delete_band'
  get 'bands/:band_id/albums/:id/delete', to: 'albums#delete', as: 'delete_band_album'
  get 'bands/:band_id/band_members/:id/delete', to: 'band_members#delete', as: 'delete_band_band_member'
  get "/takedown-guidance", to: "welcome#notification", as: "takedown_guidance"
  resources :users, only: [:edit, :update, :show]
  resources :bands do
    collection do
      match 'search' => 'bands#search', via: [:get, :post], as: :search
    end
    resources :band_members, only: [:create, :update, :destroy, :edit]
    resources :albums, only: [:new, :create, :destroy, :edit, :update] do
      resources :songs, only: [:new, :update, :edit, :create, :destroy]
    end
    resources :user_reviews, only: [:create, :update, :destroy]
    resources :events, only: [:show, :new, :update, :edit, :create, :destroy]
  end
  root 'welcome#index'
  get "/auth/:provider/callback" => 'sessions#create'
  resources :sessions, only: [:create, :destroy]
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs
  belongs_to :band
  has_many :user_review
  mount_uploader :pict, AttachmentUploader
  validates :name, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :check_user_logged_in, only: [:edit, :new, :create, :update]
  before_action only: [:edit, :create, :delete, :destroy, :new, :update] do
    check_user_got_right(@band)
  end
  def new
    find_band
    @album = @band.albums.new
  end

  def create
    find_band
    @album = @band.albums.create(album_params)
    if @album.save
      redirect_to @band
    else
      render "new", flash: { notice: 'An error occurred, please try it again' }
    end
  end

  def delete
    find_band
    @album = Album.find(params[:id])
  end

  def destroy
    find_band
    @album = Album.find(params[:id])
    @album.songs.destroy_all
    @album.destroy
    redirect_to @band
  end

  def album_params
    params.require(:album).permit(:name, :pict)
  end

  def edit
    find_band
    @album = @band.albums.find(params[:id])
  end

  def update
    find_band
    @album = @band.albums.find(params[:id])
    unless @album.update(album_params)
      render "edit", flash: { notice: 'An error occurred, please try it again' }
      return
    end
    items_order = []
    unless params[:items_order].empty?
      items_order = JSON.parse(params[:items_order])
    end
    pos = 0
    items_order.each do |item|
      song = Song.find(item)
      song.priority = pos
      if song.save
        pos += 1
      else
        render "edit", flash: { notice: 'An error occurred, please try it again' }
        return
      end
    end
    redirect_to @band
  end

  def find_band
    @band = Band.find(params[:band_id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.slim
div class="col-md-8"
  = bootstrap_form_for [@band, @album] do |f|
    .field
      == f.text_field :name
    .field
      == f.file_field :pict, hide_label:true
    =f.submit

app/views/albums/delete.html.slim
h2 "You really want to delete Album #{@album.name} ?"
= link_to 'Yeah!', band_album_path(@band, @album), :method => "DELETE", :class => "btn-default btn"

app/views/albums/edit.html.slim
div class="col-md-16"
  = bootstrap_form_for [@band, @album] do |f|
    .field
      == f.text_field :name
    .field
      == f.label 'Picture'
      br
      == f.file_field :pict, hide_label:true
    .field
      == hidden_field_tag :items_order, "", :id=>"items_ids"

    div class="col-md-8"
      -unless @album.songs.empty? 
        br
        h4 Songs:
        div class="col-md-6 sortable-items"
          ul id="sortable"
            - @album.songs.order(:priority).each do |song|
              li id=song.id
                a class="play-song" data-src=song.file_url
                  =p song.name
                = link_to edit_band_album_song_path(@band, @album, song), :class=>"song-ctrl" do
                  span class="glyphicon glyphicon-edit"
                = link_to band_album_song_path(@band, @album, song), method: :delete, :class=>"song-ctrl" do
                  span class="glyphicon glyphicon-remove-sign"
                = link_to song.file_url, :class=>"song-ctrl" do
                  span class="glyphicon glyphicon-download-alt"
      
    div
      button class="btn btn-submit" id="save_album" Save

app/views/albums/new.html.slim
= render 'form', band: @band