config/routes.rb
Rails.application.routes.draw do
  get 'invite/:link_id', to: 'band_members#invite'
  get 'bands/:id/delete', to: 'bands#delete', as: 'delete_band'
  get 'bands/:band_id/albums/:id/delete', to: 'albums#delete', as: 'delete_band_album'
  get 'bands/:band_id/band_members/:id/delete', to: 'band_members#delete', as: 'delete_band_band_member'
  get "/takedown-guidance", to: "welcome#notification", as: "takedown_guidance"
  resources :users, only: [:edit, :update, :show]
  resources :bands do
    collection do
      match 'search' => 'bands#search', via: [:get, :post], as: :search
    end
    resources :band_members, only: [:create, :update, :destroy, :edit]
    resources :albums, only: [:new, :create, :destroy, :edit, :update] do
      resources :songs, only: [:new, :update, :edit, :create, :destroy]
    end
    resources :user_reviews, only: [:create, :update, :destroy]
    resources :events, only: [:show, :new, :update, :edit, :create, :destroy]
  end
  root 'welcome#index'
  get "/auth/:provider/callback" => 'sessions#create'
  resources :sessions, only: [:create, :destroy]
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :albums
  has_many :band_members
  has_many :users, through: :band_members
  has_many :user_reviews
  has_many :events
  mount_uploader :logo, AttachmentUploader
  validates :name, presence: true
end

app/controllers/bands_controller.rb
require 'digest/sha1'
require 'pry'
class BandsController < ApplicationController
  before_action :check_user_logged_in, only: [:edit, :new, :create, :update]
  before_action only: [:edit, :update, :delete, :destroy] do
    check_user_got_right(@band)
  end

  def index
    @bands = @q.result.includes(:band_members, :albums)
  end

  def new
    @band = Band.new
    @band_member = BandMember.new
  end

  def search
    index
    render :index
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    @band.update(band_params)
    if @band.save

      redirect_to @band
    else
      redirect_to edit_band_path(@band), flash: { notice: 'An error occurred, please try it again' }
    end
  end

  def create
    @band = Band.new(band_params)
    instruments = params[:band][:band_members][:instruments].select { |value| value != "" }
    another_instrument = params[:band][:band_members][:another_instrument]
    if another_instrument == "" && instruments.empty?
      @instruments_empty = true
      render "new", flash: { notice: 'An error occurred, please try it again' }
      return
    else
      @instruments_empty = false
    end
    @band.rating = 3
    if @band.save
      link = Digest::SHA1.hexdigest [@band.id, rand].join
      @band_member = @band.band_members.new(band_member_params)
      @band_member.user = current_user
      instruments.each do |instrument|
        @band_member.instruments << Instrument.find(instrument)
      end
      @album = @band.albums.new(name: 'Basic')
      if @band_member.nickname == ""
        @band_member.nickname = current_user.name
      end
      if @band_member.save && @album.save && @band.update(:link => link)
        redirect_to @band
        return
      else
        @band.destroy
        render "new", flash: { notice: 'An error occurred, please try it again' }
        return
      end
    else
      render "new", flash: { notice: 'An error occurred, please try it again' }
      return
    end
  end

  def band_params
    params.require(:band).permit(:name, :description, :logo)
  end

  def band_member_params
    params[:band][:band_members].permit(:nickname, :instruments, :another_instrument)
  end

  def show
    @band = Band.find(params[:id])
    @band_members = @band.band_members
    @albums = @band.albums
    @reviews = @band.user_reviews.order('created_at DESC')
    unless current_user.nil?
      @new_review = UserReview.new(user: current_user)
    end
    @events = @band.events.order('date')
    @events.each do |event|
      if event.date < Date.yesterday
        event.destroy
      end
    end
    if @band.users.include?(current_user)
      @link = request.base_url + '/invite/' + @band.link
      render 'show_admin.html.slim'
    else
      @band.link = ""
    end
  end

  def delete
    @band = Band.find(params[:id])
  end

  def destroy
    @band = Band.find(params[:id])
    albums = @band.albums
    albums.destroy_all
    @band.events.destroy_all
    @band.band_members.map(&:destroy)
    @band.user_reviews.destroy_all
    @band.destroy
    redirect_to root_path
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/delete.html.slim
h2 "You really want to cancel your band #{@band.name}"
= link_to 'Yeah!', band_path(@band), :method => "DELETE", :class => "btn-default btn"

app/views/bands/edit.html.slim
div class="col col-centered"
  h1 =@band.name

div class="col-md-8"
  = bootstrap_form_for @band do |f|
    .field
      == f.text_field :name
    .field
      == f.text_area :description
    </br>
    .field
      == f.file_field :logo
    = f.submit

app/views/bands/index.html.slim
div.row
 div class="col-md-5"
  = search_form_for @q do |f|
    => f.label 'Filter by name or description'
    br
    = f.search_field :name_or_description_cont, class: "form-control"
    br
    => f.label 'Filter by nickname of member'
    br
    = f.search_field :band_members_nickname_cont, class: "form-control"
    br
    => f.label 'Filter by album'
    br
    = f.search_field :albums_name_cont, class: "form-control"
    br
    = f.submit class: 'btn btn-default'


br
div.row
  -if @bands.empty?
   h4 Sorry, band can't be found
  -else
    div.col-md-10
      table class="table"
        tr
          th.col-md-4
            =sort_link(@q, :name)
          th
            div class="col-md-4" 
              =sort_link(@q, :rating)
        tbody
          - @bands.each do |band|
            tr
              td.col-md-4
                = link_to band
                  img> src=band.logo_url class="logo-preview"
                  = p band.name 
              td.col-md-4
                div class="star-ratings-css"
                  div.star-ratings-css-top style="width: #{band.rating * 22.5}%"
                    - 7.times do
                      span ★
                  div.star-ratings-css-bottom
                    - 7.times do
                      span ★

app/views/bands/new.html.slim
div class="col col-centered"
  h1 Create new band
div class="col-md-8"
  = bootstrap_form_for @band do |f|
    .field
      == f.text_field :name, required: true
    .field
      == f.text_area :description
    .field
      == f.file_field :logo
    hr
    h3> You in band:
    = f.fields_for :band_members do |band_member|
      .field
        == band_member.text_field :nickname
      -if @instruments_empty
        div class="alert alert-danger"
          p Please select instrument or create a new one
      .field
        = band_member.select :instruments, Instrument.all.collect {|x| [x.name, x.id]},{}, {multiple: true}
      .field
        == band_member.text_field :another_instrument
      br
    = f.submit

app/views/bands/show.html.slim
div class="row"
  center
    div class="col-md-6 col-md-offset-3 band-header"
      h1 class="band-name red-name" =@band.name
      img src=@band.logo_url class="logo" 

div class="row"
  br
  div class="col-md-12 band-header"
    center 

      h4 class="band-description" =@band.description
      br
      br
div class="row"
  div class="col-centered"
    audio preload
  br

div class="row"
  div id="wrapper"
    - @albums.each do |album|
      div
        img src=album.pict_url class="album-cover" 
        h3.red-name = album.name
        
        ol
          - album.songs.order(:priority).each do |song|
            li
              a class="play-song" data-src=song.file_url
                =p song.name

    br
    br

div id="exTab2" class="container"
  ul class="nav nav-tabs"
    li class="active"
      a href="#1" data-toggle="tab" Band members
    li
      a href="#2" data-toggle="tab" Events
    li
      a href="#3" data-toggle="tab" Reviews

  div class="tab-content"
    div class="tab-pane active" id="1"
      div class="row"
        div class="col-md-12"
          br
          table class="table" id="members"
            thead
              tr
                th Name
                th Instruments
            tbody
            - @band_members.each do |member|
              tr
                td
                  = link_to member.nickname, user_path(member.user)
                td
                  -unless member.another_instrument == ""
                    =p member.another_instrument
                    -unless member.instruments.empty?
                      | ,
                  =p member.instruments.map{ |inst| inst.name }.join(', ')
                td

    div class="tab-pane" id="2"
      - @events.each do |e|
        h3
          = link_to e.event_type.name, band_event_path(@band, e)
        h4 "#{e.header}! Where? #{e.place}"
        -unless e.date == nil
          p =e.date

    div class="tab-pane" id="3"
      br
      div class="row"
        div class="col-md-6 col-md-offset-3"
          - if current_user
            = form_for [@band, @new_review] do |f|
              .field
                => f.label :rating, 'None'
                => f.radio_button :rating, -1
                - [*1..7].each do |i|
                  => f.label :rating, i
                  => f.radio_button :rating, i
              .field
                = text_area_tag :review, @new_review.review, cols:50, rows:10
              button class="btn btn-submit" id="add_review" Add review

      <br>
      div class="row"
        div class="col-md-6 col-md-offset-3"
          h2 User Reviews:
      div class="row"
        - @reviews.each do |r|
          - if r.user == current_user
            div class="row"
             div class="col-md-6 col-md-offset-3"
                = form_for [@band, r] do |f|
                    => f.label :rating, 'None'
                    => f.radio_button :rating, -1
                    - [*1..7].each do |i|
                      => f.label :rating, i
                      => f.radio_button :rating, i
                    .field
                      = text_area_tag :review, r.review, cols:50, rows:10, required:true
                    button> class="btn btn-submit" id="add_review" Edit review
                    = link_to 'Delete', band_user_review_path(@band, r), :method => "DELETE", class:"btn btn-submit"
            br
            br
          - else 
            div class="row"
              div class="col-md-6 col-md-offset-3"
                h4
                  =link_to "#{r.user.name} wrote:", user_path(r.user)
                - if r.rating > -1
                  div.star-ratings-css
                    div.star-ratings-css-top style="width: #{r.rating * 22.5}%"
                      - 7.times do
                        span ★
                    div.star-ratings-css-bottom
                      - 7.times do
                        span ★
                  br
                  br
            div class="row"
              div class="col-md-6 col-md-offset-3"
                = text_area_tag r.review, r.review, cols:50, rows:10, readonly: true

app/views/bands/show_admin.html.slim
div class="row"
  center
    div class="col-md-6 col-md-offset-3 band-header"
      h1 class="band-name red-name" =@band.name
      img src=@band.logo_url class="logo" 

div class="row"
  br
  div class="col-md-12 band-header"
    center 
      h4 class="band-description" =@band.description
      br
      = link_to 'Edit Band', edit_band_path(@band), :class => "btn-default btn"
      = link_to 'Cancel Band', delete_band_path(@band), :class => "btn-default btn"

div class="row"
  br
  div class="col-centered"
    audio preload
  br

div class="row"
  div id="wrapper"
    - @albums.each do |album|
      div
        img src=album.pict_url class="album-cover" 
        h3.red-name = album.name
        
        ol
          - album.songs.order(:priority).each do |song|
            li
              a class="play-song" data-src=song.file_url
                =p song.name
              = link_to edit_band_album_song_path(@band, album, song), :class=>"song-ctrl" do
                span class="glyphicon glyphicon-edit"
              = link_to band_album_song_path(@band, album, song), method: :delete, :class=>"song-ctrl" do
                span class="glyphicon glyphicon-remove-sign"
              = link_to song.file_url, :class=>"song-ctrl" do
                span class="glyphicon glyphicon-download-alt"
        = link_to 'Add Song', new_band_album_song_path(@band, album), :class => "btn-default btn-sm"
        = link_to 'Edit Album', edit_band_album_path(@band, album), :class => "btn-default btn-sm"
        = link_to 'Delete', delete_band_album_path(@band, album), :class => "btn-default btn-sm"

    br
    br

    = link_to 'Add Album', new_band_album_path(@band), :class => "btn-default btn"

div id="exTab2" class="container"
  ul class="nav nav-tabs"
    li class="active"
      a href="#1" data-toggle="tab" Band members
    li
      a href="#2" data-toggle="tab" Events
    li
      a href="#3" data-toggle="tab" Reviews

  div class="tab-content"
    div class="tab-pane active" id="1"
      div class="row"
        div class="col-md-12"
          br
          table class="table" id="members"
            thead
              tr
                th Name
                th Instruments
            tbody
            - @band_members.each do |member|
              tr
                td
                  = link_to member.nickname, user_path(member.user)
                td
                  -unless member.another_instrument == "" or member.another_instrument == nil
                    =p member.another_instrument
                    -unless member.instruments.empty?
                      | , 
                  =p member.instruments.map{ |inst| inst.name }.join(', ')
                td
                  = link_to 'Edit', edit_band_band_member_path(@band, member), :class => "btn-default btn-sm"
                  = link_to 'Dismiss', delete_band_band_member_path(@band, member), :class => "btn-default btn-sm"



          p Invite Your friends by sending them this link!
          input type="text" value=@link
 
    div class="tab-pane" id="2"
      - @events.each do |e|
        h3
          = link_to e.event_type.name, band_event_path(@band, e)
        h4 #{e.header}! 
        h4 #{e.place} | #{e.date}
        -unless e.date == nil
          p =e.date
        = link_to 'Edit', edit_band_event_path(@band, e), :class => "btn-default btn"
        = link_to 'Delete', band_event_path(@band, e), :method => "DELETE", :class => "btn-default btn"
        br
      = link_to 'Add Event', new_band_event_path(@band), :class => "btn-default btn"
      

    div class="tab-pane" id="3"
      br
      div class="row"
        div class="col-md-6 col-md-offset-3"
          - if @msg
            =p @msg
          = form_for [@band, @new_review] do |f|
            .field
              = text_area_tag :review, @new_review.review, cols:50, rows:10
            - if @new_review.id == nil   
              button class="btn btn-submit" id="add_review" Add review

      <br>
      div class="row"
        div class="col-md-6 col-md-offset-3"
          h2 User Reviews:
      div class="row"
        - @reviews.each do |r|
          - if r.user == current_user
            div class="row"
             div class="col-md-6 col-md-offset-3"
                = form_for [@band, r] do |f|
                    .field
                      = text_area_tag :review, r.review, cols:50, rows:10
                    button> class="btn btn-submit" id="add_review" Edit review
                    = link_to 'Delete', band_user_review_path(@band, r), :method => "DELETE", class:"btn btn-submit"
            br
            br
          - else 
            div class="row"
              div class="col-md-6 col-md-offset-3"
                h4
                  =link_to "#{r.user.name} wrote:", user_path(r.user)
                - if r.rating > -1
                  div.star-ratings-css
                    div.star-ratings-css-top style="width: #{r.rating * 22.5}%"
                      - 7.times do
                        span ★
                    div.star-ratings-css-bottom
                      - 7.times do
                        span ★
                  br
                  br
            div class="row"
              div class="col-md-6 col-md-offset-3"
                = text_area_tag r.review, r.review, cols:50, rows:10, readonly: true