config/routes.rb
Rails.application.routes.draw do
  get 'invite/:link_id', to: 'band_members#invite'
  get 'bands/:id/delete', to: 'bands#delete', as: 'delete_band'
  get 'bands/:band_id/albums/:id/delete', to: 'albums#delete', as: 'delete_band_album'
  get 'bands/:band_id/band_members/:id/delete', to: 'band_members#delete', as: 'delete_band_band_member'
  get "/takedown-guidance", to: "welcome#notification", as: "takedown_guidance"
  resources :users, only: [:edit, :update, :show]
  resources :bands do
    collection do
      match 'search' => 'bands#search', via: [:get, :post], as: :search
    end
    resources :band_members, only: [:create, :update, :destroy, :edit]
    resources :albums, only: [:new, :create, :destroy, :edit, :update] do
      resources :songs, only: [:new, :update, :edit, :create, :destroy]
    end
    resources :user_reviews, only: [:create, :update, :destroy]
    resources :events, only: [:show, :new, :update, :edit, :create, :destroy]
  end
  root 'welcome#index'
  get "/auth/:provider/callback" => 'sessions#create'
  resources :sessions, only: [:create, :destroy]
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs
  belongs_to :band
  has_many :user_review
  mount_uploader :pict, AttachmentUploader
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :albums
  has_many :band_members
  has_many :users, through: :band_members
  has_many :user_reviews
  has_many :events
  mount_uploader :logo, AttachmentUploader
  validates :name, presence: true
end

app/models/band_member.rb
class BandMember < ApplicationRecord
  belongs_to :user
  belongs_to :band
  has_and_belongs_to_many :instruments
  validates :nickname, presence: true
  validates :instruments, presence: true, unless: ->(band_member) { band_member.another_instrument.present? }
  validates :another_instrument, presence: true, unless: ->(band_member) { band_member.instruments.present? }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :event_type
  belongs_to :band
  validates :header, presence: true
  validates :text, presence: true
end

app/models/event_type.rb
class EventType < ApplicationRecord
  has_many :events
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_and_belongs_to_many :band_members
  validates :name, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  mount_uploader :file, AttachmentUploader
  validates :name, presence: true
  validates :file, presence: true
  validates :priority, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :band_members
  has_many :bands, through: :band_members
  has_many :user_reviews
  validates :name, presence: true
  mount_uploader :avatar, AttachmentUploader
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.first_name if user.name.nil? || user.name.empty?
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :band
  belongs_to :user, optional: true
  validates :review, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: -1, less_than: 8 }
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/band_members_helper.rb
module BandMembersHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyBZ9trZx7saFSStxqMpz2-ZbhZh9Qm5ZT0"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <title>MyBand</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= javascript_tag do %>
    $(document).ready(function() {
      window.$M = new (MyApp.<%= params[:controller].capitalize %> || MyApp.Base)();
      if (typeof $M.<%= params[:action] %> === 'function') {
        return $M.<%= params[:action] %>.call();
      }
    });
    <% end %>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">

        <div class="navbar-header">
          <a class="navbar-brand" href="/">MB</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li>
                <%= link_to "Start new band", new_band_path, id:"bands#new" %>
              </li>
            <% end %>

          </ul>
          <%= search_form_for @q, class:"navbar-form navbar-left" do |f| %>
            <div class="form-group">
              <%= f.search_field :name_cont, class:"form-control"%>
            </div>
            <button type="submit" class="btn btn-default">Find</button>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name%><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Options", edit_user_path(current_user.id), id: "options" %>
                  </li>
                   <li>
                    <%= link_to "Sign out", signout_path, id: "sign_out" %>
                  </li>                   

              </li>

            <% else %>
              <li>
                <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div id="content" class="container">
      <%= render partial: 'layouts/flash_messages', flash: flash %>
      <%= yield %>
    </div>


  </body>

  <footer class="footer">
    <div class="container">
      <h4>This website is school project. Please dont take it seriously!<h4>
      <%= link_to "Takedown guidance", takedown_guidance_path %>
    </div>
  </footer>

</html>